import React, { useState } from "react";
import { View, Text, Button, ActivityIndicator, ScrollView, Alert, StyleSheet } from "react-native";
import { generateSchedule, applySchedule } from "../api/client";

export function ScheduleScreen() {
  const [aiResult, setAiResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function onGenerate() {
    setLoading(true);
    setError("");
    try {
      const result = await generateSchedule();
      setAiResult(result);
    } catch (e) {
      setError(e.message || "Failed to generate schedule");
    } finally {
      setLoading(false);
    }
  }

  async function scheduleNotifications(schedule) {
    // In Expo Go we skip actual notification scheduling.
    console.log("Schedule to apply locally:", schedule);
  }

  async function onApply() {
    if (!aiResult || !aiResult.optimizedSchedule) return;

    Alert.alert(
      "Confirm schedule",
      "This schedule is generated by an AI assistant and is NOT medical advice. Have you reviewed it with a doctor?",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Apply",
          style: "destructive",
          onPress: async () => {
            try {
              await applySchedule(aiResult.optimizedSchedule);
              await scheduleNotifications(aiResult.optimizedSchedule);
              Alert.alert("Saved", "Schedule applied and reminders set.");
            } catch (e) {
              Alert.alert("Error", "Failed to apply schedule.");
            }
          }
        }
      ]
    );
  }

  return (
    <ScrollView contentContainerStyle={styles.screen}>
      <View style={styles.card}>
        <Text style={styles.title}>AI schedule assistant</Text>
        <Text style={styles.subtitle}>
          Let the assistant group medicines into a gentler daily routine. Always confirm
          changes with your doctor.
        </Text>

        <View style={styles.primaryButtonWrapper}>
          <Button
            title={loading ? "Generating..." : "Generate safe schedule & precautions"}
            onPress={onGenerate}
            disabled={loading}
            color="#0f766e"
          />
        </View>

        {error ? <Text style={styles.error}>{error}</Text> : null}

        {aiResult && (
          <View style={{ marginTop: 16 }}>
            <Text style={styles.sectionTitle}>Optimized schedule</Text>
            {(aiResult.optimizedSchedule || []).map((s, idx) => (
              <View key={idx} style={styles.scheduleRow}>
                <Text style={styles.scheduleTime}>{s.time}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={styles.scheduleMeds}>
                    {(s.medicines || []).join(", ")}
                  </Text>
                  {s.notes ? <Text style={styles.scheduleNotes}>{s.notes}</Text> : null}
                </View>
              </View>
            ))}

            <Text style={styles.sectionTitle}>Precautions</Text>
            {(aiResult.precautions || []).map((p, idx) => (
              <Text key={idx} style={styles.precaution}>
                • {p}
              </Text>
            ))}

            {aiResult.doctorWarning ? (
              <Text style={styles.warning}>{aiResult.doctorWarning}</Text>
            ) : null}

            <View style={{ marginTop: 16 }}>
              <Button title="Approve & save schedule" color="#2563eb" onPress={onApply} />
            </View>
          </View>
        )}

        {loading && (
          <View style={{ marginTop: 16 }}>
            <ActivityIndicator />
          </View>
        )}
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: {
    padding: 16,
    backgroundColor: "#f3f4f6"
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 4
  },
  subtitle: {
    fontSize: 13,
    color: "#6b7280",
    marginBottom: 12
  },
  primaryButtonWrapper: {
    marginBottom: 8
  },
  error: {
    color: "#b91c1c",
    marginTop: 4
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginTop: 8,
    marginBottom: 4
  },
  scheduleRow: {
    flexDirection: "row",
    paddingVertical: 6,
    borderBottomColor: "#e5e7eb",
    borderBottomWidth: 1
  },
  scheduleTime: {
    width: 64,
    fontWeight: "600",
    color: "#111827"
  },
  scheduleMeds: {
    fontSize: 14,
    fontWeight: "500"
  },
  scheduleNotes: {
    fontSize: 12,
    color: "#6b7280"
  },
  precaution: {
    fontSize: 14,
    color: "#374151",
    marginBottom: 4
  },
  warning: {
    marginTop: 8,
    fontSize: 13,
    color: "#b91c1c"
  }
});
